/**
 *
 * @author Asena Şahin, Halil Onur Fedai, Burak Alaydın, Barış Can
 */

package javaprogramminggame.VIEW;

import javax.swing.JButton;
import javax.swing.JLabel;

public class AboutUsView extends javax.swing.JPanel {

    /**
     * Creates new form LeaderBoardPanel
     */
    public AboutUsView() {
        initComponents();
    }
    
    public JButton getBackButton(){
        return backButton;
    }

    public JLabel getL1() {
        return l1;
    }

    public JLabel getL2() {
        return l2;
    }

    public JLabel getL3() {
        return l3;
    }

    public JLabel getL4() {
        return l4;
    }

    public JLabel getL5() {
        return l5;
    }

    public JLabel getLb0() {
        return lb0;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backButton = new javax.swing.JButton();
        lb0 = new javax.swing.JLabel();
        l1 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        l3 = new javax.swing.JLabel();
        l4 = new javax.swing.JLabel();
        l5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 255, 255));
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setSize(new java.awt.Dimension(1280, 720));

        backButton.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        backButton.setText("BACK");
        backButton.setMaximumSize(new java.awt.Dimension(200, 100));
        backButton.setMinimumSize(new java.awt.Dimension(200, 100));
        backButton.setPreferredSize(new java.awt.Dimension(200, 100));
        backButton.setSize(new java.awt.Dimension(200, 100));

        lb0.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        lb0.setForeground(new java.awt.Color(255, 51, 51));
        lb0.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb0.setMaximumSize(new java.awt.Dimension(400, 100));
        lb0.setMinimumSize(new java.awt.Dimension(400, 100));
        lb0.setPreferredSize(new java.awt.Dimension(400, 100));
        lb0.setSize(new java.awt.Dimension(400, 100));

        l1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        l1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l1.setMaximumSize(new java.awt.Dimension(400, 50));
        l1.setMinimumSize(new java.awt.Dimension(400, 50));
        l1.setPreferredSize(new java.awt.Dimension(400, 50));
        l1.setSize(new java.awt.Dimension(400, 50));

        l2.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        l2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l2.setMaximumSize(new java.awt.Dimension(400, 50));
        l2.setMinimumSize(new java.awt.Dimension(400, 50));
        l2.setPreferredSize(new java.awt.Dimension(400, 50));
        l2.setSize(new java.awt.Dimension(400, 50));

        l3.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        l3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l3.setMaximumSize(new java.awt.Dimension(400, 50));
        l3.setMinimumSize(new java.awt.Dimension(400, 50));
        l3.setPreferredSize(new java.awt.Dimension(400, 50));
        l3.setSize(new java.awt.Dimension(400, 50));

        l4.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        l4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l4.setMaximumSize(new java.awt.Dimension(400, 50));
        l4.setMinimumSize(new java.awt.Dimension(400, 50));
        l4.setPreferredSize(new java.awt.Dimension(400, 50));
        l4.setSize(new java.awt.Dimension(400, 50));

        l5.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        l5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l5.setMaximumSize(new java.awt.Dimension(400, 50));
        l5.setMinimumSize(new java.awt.Dimension(400, 50));
        l5.setPreferredSize(new java.awt.Dimension(400, 50));
        l5.setSize(new java.awt.Dimension(400, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l5, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l4, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l3, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l2, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l1, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb0, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(310, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(l1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(309, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l4;
    private javax.swing.JLabel l5;
    private javax.swing.JLabel lb0;
    // End of variables declaration//GEN-END:variables
}
